services: 
  fileupload-srv:
    image: spring-file-upload:v1.0.0
    build: 
     context: . 
     dockerfile: dev.Dockerfile
     args: 
      - PORT=${APP_PORT:-8080}
    # environment: 
    pull_policy: build
    volumes: 
      - image-backup-vol:/app/filestorage/images
    ports: 
      - 8080:${APP_PORT:-8080}
volumes: 
  image-backup-vol:
