spring:
    application:
        name: filestorageservice
springdoc: 
    swagger-ui: 
        path: / 
    api-docs: 
        path: /v3/api-docs
server:
    port: 8282
file:
  upload-img-dir: filestorage/images/
  upload-img-client: /images/**
  upload-file-dir: filestorage/data/